HouseHunting/HouseHunt/HouseHunt/urls.py
from django.contrib import admin
from django.urls import path, include
from loging import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'), name='home'),
    path('login/' ,include('loging.urls'), name="login"),
]

HouseHunting/HouseHunt/home/urls.py
from nturl2path import url2pathname
from django.urls import path

from home import views

app_name = 'home'

urlpatterns = [
    path('',views.index,name='home'),
    path('featured/', views.featured, name='featured'),
]

HouseHunting/HouseHunt/loging/urls.py
from django.urls import path

from loging import views

app_name = 'login'

urlpatterns = [
    path('', views.LoginFormView.as_view(), name="LoginForm"),
    path('login/', views.login_user, name='login_user'),
    # path('thanks/', views.rev, name='thanks_page'),
]

HouseHunting/HouseHunt/accounts/models.py
from django.db import models

# Create your models here.

HouseHunting/HouseHunt/home/models.py
from email.policy import default
from django.db import models

# Create your models here.

class Property(models.Model):

    # NOT migrated yet
    b0 = 'unknown'
    b1 = '1 BHK'
    b2 = '2 BHK'
    b3 = '3 BHK'
    b4 = '4 BHK'

    room_type = [
        (b0, 'unknown'),
        (b1, '1 BHK'),
        (b2, '2 BHK'),
        (b3, '3 BHK'),
        (b4, '4 BHK'),
    ]
    # -------------------------------------------------------
    unknown_state = 'unknown'
    rtm = 'Ready to move'
    undercon = 'Under Construction'
    fur = 'Furnished'
    semifur = 'Semi-Furnished'
    unfur = 'Unfurnished'

    state = [
        (unknown_state, 'unknown'),
        (rtm, 'Ready To Move'),
        (undercon, 'Under Construction'),
        (fur, 'Furnished'),
        (semifur, 'Semi-Furnished'),
        (unfur,'Unfurnished'),
    ]
    # ------------------------------------------------------------
    unknown_type = 'Type Unknown'
    flat = 'Flat'
    house = 'House'
    shop = 'Shop'
    warehouse = 'Warehouse'
    land = 'Land(Plot)'

    type_of_estate = [
        (unknown_type,'Type Unknown'),
        (flat ,'Flat'),
        (house ,'House'),
        (shop,'Shop'),
        (warehouse ,'Warehouse'),
        (land, 'Land(Plot)'),
    ]

    # -------------------------------------------------------------
    unknown_purpose = 'unknown'
    for_sell = 'SELL'
    for_buy = 'BUY'
    for_rent = 'RENT'

    for_purpose = [
        (unknown_purpose,'unknown'),
        (for_sell, 'SELL'),
        (for_buy, 'BUY'),
        (for_rent, 'RENT')
    ]

    user_mail = models.ForeignKey("loging.TenentUser", on_delete=models.CASCADE)
    mobile = models.IntegerField()
    price = models.IntegerField()
    BHK = models.CharField(choices=room_type, max_length=7, default=b0)
    location = models.CharField(max_length=100)
    status = models.CharField(choices=state, max_length=20, default=unknown_state)
    prop_type = models.CharField(choices=type_of_estate, max_length=20, default=unknown_type)
    city =  models.CharField(max_length=30)
    for_sell_or_rent =  models.CharField(choices=for_purpose,default= unknown_purpose, max_length=20)
    image = models.ImageField(upload_to='User_Images/')
    prop_number = models.CharField(max_length=30)

    def __str__(self):
        return self.location

HouseHunting/HouseHunt/loging/models.py
from django.db import models
from django.contrib.auth.hashers import make_password
from django.urls import reverse

# Create your models here.

class TenentUser(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    OTHERS = 'O'

    GEN = [
        (MALE, 'Male'),
        (FEMALE, 'Female'),
        (OTHERS, 'Prefer not to say'),
    ]

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()
    password = models.CharField(max_length=100,null=False, default='adm123')
    gender = models.CharField(choices=GEN, max_length=20, default=OTHERS)

    def __str__(self):
        return self.first_name

    # def get_absolute_url(self):
    #     return reverse("loging/thank")
    

    def save(self, *args, **kwargs):
        self.password = make_password(self.password)
        super(TenentUser, self).save(*args, **kwargs)

    emp_auth = models.Manager()

HouseHunting/HouseHunt/loging/forms.py
from django import forms
from loging.models import TenentUser

# Define your forms here

class LoginForm(forms.ModelForm):
    class Meta:
        model = TenentUser
        fields = ['email', 'password']

HouseHunting/HouseHunt/accounts/views.py
from django.shortcuts import render

# Create your views here.

HouseHunting/HouseHunt/home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'home/home1.html')

def featured(request):
    return render(request, 'home/featured.html')

HouseHunting/HouseHunt/loging/views.py
from django.shortcuts import render
from loging.models import TenentUser
from django.views.generic.edit import FormView
from loging.forms import LoginForm

# Create your views here.

def index(request):
    return render(request, "loging/home.html",{})

def rev(request):
    return render(request, "loging/thanks.html",{})

class LoginFormView(FormView):
    template_name = 'loging/account.html' # 'loging/login.html'
    form_class = LoginForm
    # success_url = 'home1.html'

def login_user(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        try:
            user = TenentUser.emp_auth.get(email=email, password=password)
            if user is not None:
                return render(request, 'thanks.html', {})
            else:
                print('Invalid user')
        except Exception as identifier:
            return render(request, 'loging/home.html')
    else:
        return render(request, 'loging/login.html')

HouseHunting/HouseHunt/home/templates/home/featured.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>complete responsive real estate website design tutorial</title>

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- custom css file link  -->
    <!--<link rel="stylesheet" href="featured.css">-->
    <link rel="stylesheet" href="{% static 'css/featured.css' %}">


</head>
<body>
    
<!-- header section starts  -->

<header>

    <a href="#" class="logo"><span>House</span>hunting</a>

    <nav class="navbar">
        <a href="{% url 'home:home' %}">home</a>
        <a href="services.html">services</a>
        <a href="{% url 'home:featured'%}">featured</a>
        <a href="agents.html">agents</a>
        <a href="contact.html">contact</a>
    </nav>

    <div class="icons">
        <div id="menu-bars" class="fas fa-bars"></div>
        <a href="#" class="fas fa-heart"></a>
        <a href="#" class="fas fa-user"></a>
    </div>

</header>

<!-- header section ends -->



<!-- featured section starts  -->

<section class="featured" id="featured">

    <h1 class="heading"> <span>featured</span> properties </h1>

    <div class="box-container">

        <div class="box">
            <div class="image-container">
                <!--<img src="images/img-1.jpg" alt="">-->
                <img src="{% static 'images/img-1.jpg'%}" alt="">

                <div class="info">
                    <h3>3 days ago</h3>
                    <h3>for rent</h3>
                </div>
                <div class="icons">
                    <a href="#" class="fas fa-film"><h3>1</h3></a>
                    <a href="#" class="fas fa-camera"><h3>4</h3></a>
                </div>
            </div>
            <div class="content">
                <div class="price">
                    <h3>$25,000/mo</h3>
                    <a href="#" class="fas fa-heart"></a>
                    <a href="#" class="fas fa-envelope"></a>
                    <a href="#" class="fas fa-phone"></a>
                </div>
                <div class="location">
                    <h3>modern apartments</h3>
                    <p>jogeshwari west, mumbai, india - 400104</p>
                </div>
                <div class="details">
                    <h3> <i class="fas fa-expand"></i> 3500 sqft </h3>
                    <h3> <i class="fas fa-bed"></i> 3 beds </h3>
                    <h3> <i class="fas fa-bath"></i> 2 baths </h3>
                </div>
                <div class="buttons">
                    <a href="#" class="btn">request info</a>
                    <a href="#" class="btn">view details</a>
                </div>
            </div>
        </div>

        <div class="box">
            <div class="image-container">
                <img src="{% static 'images/img-2.jpg'%}" alt="">
                <div class="info">
                    <h3>6 days ago</h3>
                    <h3>for sell</h3>
                </div>
                <div class="icons">
                    <a href="#" class="fas fa-film"><h3>2</h3></a>
                    <a href="#" class="fas fa-camera"><h3>7</h3></a>
                </div>
            </div>
            <div class="content">
                <div class="price">
                    <h3>$25,000/mo</h3>
                    <a href="#" class="fas fa-heart"></a>
                    <a href="#" class="fas fa-envelope"></a>
                    <a href="#" class="fas fa-phone"></a>
                </div>
                <div class="location">
                    <h3>modern apartments</h3>
                    <p>jogeshwari west, mumbai, india - 400104</p>
                </div>
                <div class="details">
                    <h3> <i class="fas fa-expand"></i> 3500 sqft </h3>
                    <h3> <i class="fas fa-bed"></i> 3 beds </h3>
                    <h3> <i class="fas fa-bath"></i> 2 baths </h3>
                </div>
                <div class="buttons">
                    <a href="#" class="btn">request info</a>
                    <a href="#" class="btn">view details</a>
                </div>
            </div>
        </div>

        <div class="box">
            <div class="image-container">
                <img src="{% static 'images/img-3.jpg'%}" alt="">
                <div class="info">
                    <h3>1 days ago</h3>
                    <h3>for rent</h3>
                </div>
                <div class="icons">
                    <a href="#" class="fas fa-film"><h3>1</h3></a>
                    <a href="#" class="fas fa-camera"><h3>6</h3></a>
                </div>
            </div>
            <div class="content">
                <div class="price">
                    <h3>$25,000/mo</h3>
                    <a href="#" class="fas fa-heart"></a>
                    <a href="#" class="fas fa-envelope"></a>
                    <a href="#" class="fas fa-phone"></a>
                </div>
                <div class="location">
                    <h3>modern apartments</h3>
                    <p>jogeshwari west, mumbai, india - 400104</p>
                </div>
                <div class="details">
                    <h3> <i class="fas fa-expand"></i> 3500 sqft </h3>
                    <h3> <i class="fas fa-bed"></i> 3 beds </h3>
                    <h3> <i class="fas fa-bath"></i> 2 baths </h3>
                </div>
                <div class="buttons">
                    <a href="#" class="btn">request info</a>
                    <a href="#" class="btn">view details</a>
                </div>
            </div>
        </div>

        <div class="box">
            <div class="image-container">
                <img src="{% static 'images/img-4.jpg'%}" alt="">
                <div class="info">
                    <h3>9 days ago</h3>
                    <h3>for rent</h3>
                </div>
                <div class="icons">
                    <a href="#" class="fas fa-film"><h3>2</h3></a>
                    <a href="#" class="fas fa-camera"><h3>6</h3></a>
                </div>
            </div>
            <div class="content">
                <div class="price">
                    <h3>$25,000/mo</h3>
                    <a href="#" class="fas fa-heart"></a>
                    <a href="#" class="fas fa-envelope"></a>
                    <a href="#" class="fas fa-phone"></a>
                </div>
                <div class="location">
                    <h3>modern apartments</h3>
                    <p>jogeshwari west, mumbai, india - 400104</p>
                </div>
                <div class="details">
                    <h3> <i class="fas fa-expand"></i> 3500 sqft </h3>
                    <h3> <i class="fas fa-bed"></i> 3 beds </h3>
                    <h3> <i class="fas fa-bath"></i> 2 baths </h3>
                </div>
                <div class="buttons">
                    <a href="#" class="btn">request info</a>
                    <a href="#" class="btn">view details</a>
                </div>
            </div>
        </div>

        <div class="box">
            <div class="image-container">
                <img src="{% static 'images/img-5.jpg'%}" alt="">
                <div class="info">

                    <h3>10 days ago</h3>
                    <h3>for sell</h3>
                </div>
                <div class="icons">
                    <a href="#" class="fas fa-film"><h3>3</h3></a>
                    <a href="#" class="fas fa-camera"><h3>8</h3></a>
                </div>
            </div>
            <div class="content">
                <div class="price">
                    <h3>$25,000/mo</h3>
                    <a href="#" class="fas fa-heart"></a>
                    <a href="#" class="fas fa-envelope"></a>
                    <a href="#" class="fas fa-phone"></a>
                </div>
                <div class="location">
                    <h3>modern apartments</h3>
                    <p>jogeshwari west, mumbai, india - 400104</p>
                </div>
                <div class="details">
                    <h3> <i class="fas fa-expand"></i> 3500 sqft </h3>
                    <h3> <i class="fas fa-bed"></i> 3 beds </h3>
                    <h3> <i class="fas fa-bath"></i> 2 baths </h3>
                </div>
                <div class="buttons">
                    <a href="#" class="btn">request info</a>
                    <a href="#" class="btn">view details</a>
                </div>
            </div>
        </div>

        <div class="box">
            <div class="image-container">
                <img src="{% static 'images/img-6.jpg'%}" alt="">
                <div class="info">
                    <h3>3 days ago</h3>
                    <h3>for sell</h3>
                </div>
                <div class="icons">
                    <a href="#" class="fas fa-film"><h3>1</h3></a>
                    <a href="#" class="fas fa-camera"><h3>4</h3></a>
                </div>
            </div>
            <div class="content">
                <div class="price">
                    <h3>$25,000/mo</h3>
                    <a href="#" class="fas fa-heart"></a>
                    <a href="#" class="fas fa-envelope"></a>
                    <a href="#" class="fas fa-phone"></a>
                </div>
                <div class="location">
                    <h3>modern apartments</h3>
                    <p>jogeshwari west, mumbai, india - 400104</p>
                </div>
                <div class="details">
                    <h3> <i class="fas fa-expand"></i> 3500 sqft </h3>
                    <h3> <i class="fas fa-bed"></i> 3 beds </h3>
                    <h3> <i class="fas fa-bath"></i> 2 baths </h3>
                </div>
                <div class="buttons">
                    <a href="#" class="btn">request info</a>
                    <a href="#" class="btn">view details</a>
                </div>
            </div>
        </div>

    </div>
    
</section>

<!-- featured section ends -->


<!-- footer section starts  -->

<section class="footer">

    <div class="footer-container">

        <div class="box-container">

            <div class="box">
                <h3>branch location</h3>
                <a href="#">india</a>
                <a href="#">USA</a>
                <a href="#">france</a>
                <a href="#">russia</a>
                <a href="#">japan</a>
            </div> 
            
            <div class="box">
                <h3>quick links</h3>
                <a href="home.html">home</a>
                <a href="services.html">services</a>
                <a href="featured.html">featured</a>
                <a href="agents.html">agents</a>
                <a href="contact.html">contact</a>
            </div> 

            <div class="box">
                <h3>extra links</h3>
                <a href="account.html">my account</a>
                <a href="#">my favorite</a>
                <a href="#">my list</a>
            </div> 

            <div class="box">
                <h3>follow us</h3>
                <a href="#">facebook</a>
                <a href="#">twitter</a>
                <a href="#">instagram</a>
                <a href="#">linkedin</a>
            </div> 

        </div>

        <div class="credit">all rights reserved! </div>

    </div>

</section>

<!-- footer section ends -->




<!-- javascript part  -->
<script>

let menu = document.querySelector('#menu-bars');
let navbar = document.querySelector('.navbar');

menu.onclick = () =>{
    navbar.classList.toggle('active');
    menu.classList.toggle('fa-times');
}

window.onscroll = () =>{
    navbar.classList.remove('active');
    menu.classList.remove('fa-times');
}

</script>

</body>
</html>

HouseHunting/HouseHunt/home/templates/home/home1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Househunting.com</title>

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- custom css file link  -->
    <!--<link rel="stylesheet" href="home1.css">-->
    <link rel="stylesheet" href="{% static 'css/home1.css' %}">


</head>
<body>
    
<!-- header section starts  -->

<header>

    <a href="#" class="logo"><span>House</span>hunting</a>

    <nav class="navbar">
        <a href="{% url 'home:home' %}">home</a>
        <a href="services.html">services</a>
        <a href="{% url 'home:featured' %}">featured</a>
        <a href="agents.html">agents</a>
        <a href="contact.html">contact</a>
    </nav>

    <div class="icons">
        <div id="menu-bars" class="fas fa-bars"></div>
        <a href="#" class="fas fa-heart"></a>
        <a href="{% url 'login:LoginForm' %}" class="fas fa-user"></a>
    </div>

</header>

<!-- header section ends -->

<!-- home section starts  -->

<section class="home" id="home">

    <form action="">

        <h3>find your perfect home</h3>

        <div class="buttons-container">
            <a href="#" class="btn">for rent</a>
            <a href="#" class="btn">for sell</a>
        </div>

        <div class="inputBox">
            <input type="search" name="" placeholder="city" id="">
            <input type="search" name="" placeholder="city" id="">
            <select name="" id="">
                <option value="" disabled hidden selected>minimum price</option>
                <option value="$5000">$5000</option>
                <option value="$10000">$10000</option>
                <option value="$15000">$15000</option>
                <option value="$20000">$20000</option>
                <option value="$25000">$25000</option>
            </select>
            <select name="" id="">
                <option value="" disabled hidden selected>maximum price</option>
                <option value="$30000">$30000</option>
                <option value="$35000">$35000</option>
                <option value="$40000">$40000</option>
                <option value="$45000">$45000</option>
                <option value="$50000">$50000</option>
            </select>
            <select name="" id="">
                <option value="" disabled hidden selected>property status</option>
                <option value="Ready To Move">Ready To Move</option>
                <option value="under construction">under construction</option>
                <option value="furnished">furnished</option>
                <option value="semi-furnished">semi-furnished</option>
                <option value="unfurnished">unfurnished</option>
            </select>
            <select name="" id="">
                <option value="" disabled hidden selected>property type</option>
                <option value="flat">flat</option>
                <option value="house">house</option>
                <option value="shop">shop</option>
                <option value="warehouse">warehouse</option>
                <option value="land">land</option>
            </select>
            <select name="" id="">
                <option value="" disabled hidden selected>BHK</option>
                <option value="1 BHK">1 BHK</option>
                <option value="2 BHK">2 BHK</option>
                <option value="3 BHK">3 BHK</option>
                <option value="4 BHK">4 BHK</option>
                <option value="5 BHK">5 BHK</option>
            </select>
            <select name="" id="">
                <option value="" disabled hidden selected>aminities</option>
                <option value="parking space">parking space</option>
                <option value="swimming pool">swimming pool</option>
                <option value="playground">playground</option>
                <option value="security">security</option>
                <option value="all">all</option>
            </select>
            <select name="" id="">
                <option value="" disabled hidden selected>bedrooms</option>
                <option value="1 bedroom">1 bedroom</option>
                <option value="2 bedroom">2 bedroom</option>
                <option value="3 bedroom">3 bedroom</option>
                <option value="4 bedroom">4 bedroom</option>
                <option value="5 bedroom">5 bedroom</option>
            </select>
            <select name="" id="">
                <option value="" disabled hidden selected>bathrooms</option>
                <option value="1 bathroom">1 bathroom</option>
                <option value="2 bathroom">2 bathroom</option>
                <option value="3 bathroom">3 bedroom</option>
                <option value="4 bathroom">4 bathroom</option>
                <option value="5 bathroom">5 bathroom</option>
            </select>
        </div>

        <input type="submit" value="search property" class="btn">

    </form>

</section>

<!-- home section ends -->





<!-- footer section starts  -->

<section class="footer">

    <div class="footer-container">

        <div class="box-container">

            <div class="box">
                <h3>branch location</h3>
                <a href="#">india</a>
                <a href="#">USA</a>
                <a href="#">france</a>
                <a href="#">russia</a>
                <a href="#">japan</a>
            </div> 
            
            <div class="box">
                <h3>quick links</h3>
                <a href="#">home</a>
                <a href="#">services</a>
                <a href="#">featured</a>
                <a href="#">agents</a>
                <a href="#">contact</a>
            </div> 

            <div class="box">
                <h3>extra links</h3>
                <a href="#">my account</a>
                <a href="#">my favorite</a>
                <a href="#">my list</a>
            </div> 

            <div class="box">
                <h3>follow us</h3>
                <a href="#">facebook</a>
                <a href="#">twitter</a>
                <a href="#">instagram</a>
                <a href="#">linkedin</a>
            </div> 

        </div>

        <div class="credit">all rights reserved! </div>

    </div>

</section>

<!-- footer section ends -->


















<!-- javascript part  -->
<script>

let menu = document.querySelector('#menu-bars');
let navbar = document.querySelector('.navbar');

menu.onclick = () =>{
    navbar.classList.toggle('active');
    menu.classList.toggle('fa-times');
}

window.onscroll = () =>{
    navbar.classList.remove('active');
    menu.classList.remove('fa-times');
}

</script>

</body>
</html>

HouseHunting/HouseHunt/loging/templates/account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Househunting.com\Account</title>

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href="templates/account.css">

</head>
<body>
    
<!-- header section starts  -->

<header>

    <a href="#" class="logo"><span>House</span>hunting</a>

    <nav class="navbar">
        <a href="#home">home</a>
        <a href="#services">services</a>
        <a href="#featured">featured</a>
        <a href="#agents">agents</a>
        <a href="#contact">contact</a>
    </nav>

    <div class="icons">
        <div id="menu-bars" class="fas fa-bars"></div>
        <a href="#" class="fas fa-heart"></a>
        <a href="#" class="fas fa-user"></a>
    </div>

</header>

<!-- header section ends -->


<!-- account section starts  -->

<section class="account">
    <div class="account-container">
        <div class="col-2">
            <div class="form-btn">
                <span onclick="login()">Login</span>
                <span onclick="register()">Register</span>
                <hr id="Indicator">
            </div>
            <div class="inputBox">
                <form id="LoginForm">
                    
                    <input type="text" placeholder="Username">
                    <input type="password" placeholder="Password">
                    <button type="submit" class="btn">Login</button>
                    <a href="">Forgot Password</a>
                </form>
                <form id="RegForm">
                    
                    <input type="text" placeholder="First Name">
                    <input type="text" placeholder="Last name">
                    <input type="number" placeholder="Mobile No.">
                
                    <input type="email" placeholder="Email">
                    <input type="password" id='pass' placeholder="Password">
                    <input type="password" id='confirmpass'placeholder="Confirmed Password">
                    <button type="submit" class="btn">Register</button>
                
                </form>
            
        </div>
    </div>

</section>



<!-- account section ends -->

<!-- footer section starts  -->

<section class="footer">

    <div class="footer-container">

        <div class="box-container">

            <div class="box">
                <h3>branch location</h3>
                <a href="#">india</a>
                <a href="#">USA</a>
                <a href="#">france</a>
                <a href="#">russia</a>
                <a href="#">japan</a>
            </div> 
            
            <div class="box">
                <h3>quick links</h3>
                <a href="#">home</a>
                <a href="#">services</a>
                <a href="#">featured</a>
                <a href="#">agents</a>
                <a href="#">contact</a>
            </div> 

            <div class="box">
                <h3>extra links</h3>
                <a href="#">my account</a>
                <a href="#">my favorite</a>
                <a href="#">my list</a>
            </div> 

            <div class="box">
                <h3>follow us</h3>
                <a href="#">facebook</a>
                <a href="#">twitter</a>
                <a href="#">instagram</a>
                <a href="#">linkedin</a>
            </div> 

        </div>

        <div class="credit">all rights reserved! </div>

    </div>

</section>

<!-- footer section ends -->



<!-- javascript part  -->
<script>

let menu = document.querySelector('#menu-bars');
let navbar = document.querySelector('.navbar');

menu.onclick = () =>{
    navbar.classList.toggle('active');
    menu.classList.toggle('fa-times');
}

window.onscroll = () =>{
    navbar.classList.remove('active');
    menu.classList.remove('fa-times');
}

</script>
<script>
    var LoginForm = document.getElementById("LoginForm");
    var RegForm = document.getElementById("RegForm");
    var Indicator = document.getElementById("Indicator");

   
    function login(){
        LoginForm.style.transform="translateX(300px)";
        RegForm.style.transform="translateX(300px)";
        Indicator.style.transform="translateX(0px)";    
    }
    function register(){
        RegForm.style.transform="translateX(-500px)";
        LoginForm.style.transform="translateX(-500px)"; 
        Indicator.style.transform="translateX(100px)"; 
    }
</script>
</body>
</html>

HouseHunting/HouseHunt/loging/templates/login.html
<html>
<body>
    <from action='.' method='POST'>
        {% csrf_token %}
        
        {% for field in form %}
            {% if field == 'email' %}
                <input type='email'>
            {% else %}
                <input type='password'>
            {% endif %}
        {% endfor %}
        <input type='submit' value='submit'>
    </form>
</body>
</html>

HouseHunting/HouseHunt/loging/templates/loging/login.html
<html>
<body>
    <form action="{% url 'home:home'%}"method='post'>
        {% csrf_token %}
        {% for field in form %}
        <tr>
          {% if field.name == 'email' %}
          <th><label for="id_email">Email:</label></th>
          <td>
            <input type="email" name="email" maxlength="254" required id="id_email">
          </td>
          {% else %}

          <th><label for="id_password">Password:</label></th>
          <td>
            <input type="password" name="password"  maxlength="30" required id="id_password">
          </td>
          {% endif %}
        </tr>
        {% endfor %}
        <button type="submit">login</button>
    </form>
</body>
</html>

HouseHunting/HouseHunt/loging/templates/loging/thanks.html
<html>
<h1>You Have signed in/ Logged in {{ form }}</h1>
</html>